### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by iliakan** [sahinyanlik/javascript-tutorial-tr#1]
I see lots of stuff has been translated.
When the first part is finished, how about to publish it?

Also, are you sure it's worth to translate the code? 

People in Turkey use Turkish names and stuff in the code, not English ones?

**Comment by iliakan** [comment]
@sahinyanlik

**Comment by sahinyanlik** [comment]
Yes maybe I should have skip them. I would like to publish. But whenever I try to publish I had some problem with deploying your project. I was going to ask help for it.

**Comment by iliakan** [comment]
Add @iliakan to collaborators please.

**Comment by iliakan** [comment]
I'll make minor changes and test the deployment.

**Comment by sahinyanlik** [comment]
I did.

**Comment by iliakan** [comment]
I just checked https://github.com/iliakan/javascript-tutorial-server/, works great with your tutorial.

Let me know if you have problems.

**Comment by sahinyanlik** [comment]
Thanks I will give it a try when I have free time. Thanks
