### ISSUE TITLE
Beraber devam etmek

### ISSUE THREAD

**Issue by berat** [sahinyanlik/javascript-tutorial-tr#12]
Merhaba, İngilizcemi geliştirmek için İngilizce makaleleri Türkçeye çeviriyorum. Normal makaledense birilerine faydalı olmak için bu repoyu tercih ettim. İsterseniz şu an çevirim için çalıştığınız makale varsa onu projects kısmı ile belirlersek çok iyi olur. Çakışmaları önleyebiliriz.

**Comment by sahinyanlik** [comment]
Merhaba Berat
Geliştirme buradan devam etmiyor aslında https://github.com/javascript-tutorial/tr.javascript.info/issues/1 burayı okuyup. Sonrasında hangi bölümü değiştirmek istiyorsan altına yorum olarak ekleyebilirsin. Yardımların için şimdiden teşekkür ederim.

**Comment by berat** [comment]
Oraya pull ettim fakat fazla aktif değil sanırım.

**Comment by sahinyanlik** [comment]
İşim vardı da . Şimdi bakabiliyorum.
