### ISSUE TITLE
Publishing

### ISSUE THREAD

**Issue by iliakan** [sahinyanlik/javascript-tutorial-tr#5]
Hi,

How about to finish translating the first part and publish the turkish tutorial?

**Comment by sahinyanlik** [comment]
I published but didn't buy the domain yet. I will buy it soon. I was going to ask you if I can sell it as epub and pdf as you do? Or is it against the licence ?

**Comment by iliakan** [comment]
I can publish it at tr.javascript.info, as a part of the project, and 50% of epub/pdf sales will be yours.
